#!/bin/bash

yes Y | apt-get install polipo -y

mkdir /usr/local/etc/polipo/

curl -o /usr/local/etc/polipo/config https://raw.githubusercontent.com/bosxixi/scripts/master/polipo.config

sudo ln -sfv /usr/local/etc/polipo/config /etc/polipo/config

echo 'polipo stopping'

service polipo stop

echo 'polipo starting'

service polipo start

yes Y | apt-get install supervisor -y

echo 'install supervisor'

cat >> /etc/supervisor/supervisord.conf

[inet_http_server]
port=0.0.0.0:9001
username=admin
password=xboxone


^D

echo 'supervisor restart'
service supervisor restart
