#!/bin/bash

yes Y | apt-get install polipo -y

mkdir /usr/local/etc/polipo/

wget -O /usr/local/etc/polipo/config https://raw.githubusercontent.com/bosxixi/scripts/master/polipo.config

sudo ln -sfv /usr/local/etc/polipo/config /etc/polipo/config

echo 'polipo stopping'

service polipo stop

echo 'polipo starting'

service polipo start

yes Y | apt-get install supervisor -y

echo 'install supervisor'

wget -O /etc/supervisor/supervisord.conf https://raw.githubusercontent.com/bosxixi/scripts/master/supervisor.config

echo 'supervisor restart'
service supervisor restart
