#!/bin/bash

echo 'download services artifacts'

yes Y | apt-get install unzip -y

yes Y | apt-get install polipo -y

mkdir /usr/local/etc/polipo/

wget -O /usr/local/etc/polipo/config https://raw.githubusercontent.com/bosxixi/scripts/master/polipo.config

sudo ln -sfv /usr/local/etc/polipo/config /etc/polipo/config

echo 'polipo stopping'

service polipo stop

echo 'polipo starting'

service polipo start

yes Y | apt-get install supervisor -y

echo 'install supervisor'

wget -O /etc/supervisor/supervisord.conf https://raw.githubusercontent.com/bosxixi/scripts/master/supervisor.config

echo 'supervisor restart'
service supervisor restart

yes Y | apt-get install python-pip -y
pip install git+https://github.com/shadowsocks/shadowsocks.git@master

echo 'dwonloading services...'

curl http://youtubedl.scorpioplayer.com/dl/ms.zip --output /home/ms.zip
wget -O /etc/ss.json https://raw.githubusercontent.com/bosxixi/scripts/master/ss.json
wget -O /etc/supervisor/conf.d/ss.conf https://raw.githubusercontent.com/bosxixi/scripts/master/services/ss.conf
wget -O /etc/supervisor/conf.d/ms.conf https://raw.githubusercontent.com/bosxixi/scripts/master/services/ms.conf

yes Y | unzip ms.zip -d /home/ms

sudo chmod +x /home/ms/movableservice/publish/MovableService

echo 'restart services...'
supervisorctl reread
supervisorctl update

supervisorctl start ms
