#!/bin/bash

yes Y | apt-get update

echo 'download services artifacts'

yes Y | apt-get install unzip -y

yes Y | apt-get install polipo -y

mkdir /usr/local/etc/polipo/

wget -O /usr/local/etc/polipo/config https://raw.githubusercontent.com/bosxixi/scripts/master/src/polipo.config

sudo ln -sfv /usr/local/etc/polipo/config /etc/polipo/config

echo 'polipo stopping'

service polipo stop

echo 'polipo starting'

service polipo start

yes Y | apt-get install supervisor -y

echo 'install supervisor'

wget -O /etc/supervisor/supervisord.conf https://raw.githubusercontent.com/bosxixi/scripts/master/src/supervisor.config

echo 'supervisor restart'

service supervisor restart

yes Y | apt-get install python-pip -y

pip install git+https://github.com/shadowsocks/shadowsocks.git@master

echo 'dwonloading services...'

curl http://youtubedl.scorpioplayer.com/dl/ms.zip --output /home/ms.zip

yes Y | unzip ms.zip -d /home/ms

sudo chmod +x /home/ms/movableservice/publish/MovableService

wget -O /etc/ss.json https://fs.scorpioplayer.com/dl/scripts/ss.json

wget -O /etc/supervisor/conf.d/ss.conf https://raw.githubusercontent.com/bosxixi/scripts/master/src/services/ss.conf

wget -O /etc/supervisor/conf.d/ms.conf https://raw.githubusercontent.com/bosxixi/scripts/master/src/services/ms.conf




echo 'restart services...'

supervisorctl reread

supervisorctl update

supervisorctl start ms
