#!/bin/bash

echo 'stop services...'

supervisorctl stop ms

echo 'downloading services...'

curl https://fs.scorpioplayer.com/dl/files/ms.zip --output /home/ms.zip

yes Y | unzip /home/ms.zip -d /home/ms

sudo chmod +x /home/ms/movableservice/publish/MovableService

echo 'restart services...'

supervisorctl reread

supervisorctl update

supervisorctl start ms
